<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .centered {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            text-align: center;
            margin-top: 40px;
        }

        .generatedby {
            position: absolute;
            top: 130px;
            left: 40px;
        }

        .dateGenerated {
            position: absolute;
            top: 130px;
            right: 40px;
        }

        table {
            width: 90%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 4px;
            text-align: center;
        }

        th {
            background-color: #ffffff;
            color: #000000;
            font-weight: bold;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer{
            width: 300px;
            height: 60px;
            position: absolute;
            bottom: 40px;
            right: 40px;
        }
    </style>
</head>

<body>
    <div class="centered">
        <div>ALTURAS GROUP OF COMPANIES</div>
        <div>ALTURAS MALL</div>
        <div>Verified Gift Check Report</div>
        <div>From {{$d1}} to {{$d2}}</div>
    </div>
    <div class="generatedby">
        <span style="font-weight: bold;">Generated By: </span>{{$generatedby}}
    </div>
    <div class="dateGenerated">
        <span style="font-weight: bold;">Date Generated: </span>{{$dateGenerated}}
    </div>
    <div style="margin-top: 70px ;width: 100%; margin-left:40px; margin-right:40px">
        <table>
            <thead>
                <tr>
                    <th>Barcode #</th>
                    <th>Denom</th>
                    <th>GC Type</th>
                    <th>Customer</th>
                    <th>Status</th>
                    <th>Balance</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $item)
                    <tr>
                        <td>{{ $item['vs_barcode'] }}</td>
                        <td>{{ $item['vs_tf_denomination'] }}</td>
                        <td>
                            @if($item['vs_gctype'] == '1')
                                Regular
                            @elseif($item['vs_gctype'] == '2')
                                Promo
                            @elseif($item['vs_gctype'] == '3')
                                Special External
                            @elseif($item['vs_gctype'] == '6')
                                Beam and Go
                            @endif
                        </td>
                        <td>{{$item['customer']}}</td>
                        <td>{{$item['vs_tf_used'] =='*' ? 'Used' : ''}}</td>
                        <td>{{$item['vs_tf_balance']}}</td>
                        <td>{{$item['vs_date']}}</td>
                    </tr>
                @endforeach

            </tbody>
        </table>

        <div class="footer">
            <div>Checked by:</div>
            <hr style="border: 1px solid black; width: 70%; margin: 10px auto;">
            <div style="text-align: center">(Signature Over Printed Name)</div>
        </div>
    </div>
</body>

</html>

